### ISSUE TITLE
[rust] Update extension to be compatible with latest Theia version

### ISSUE THREAD

**Issue by njskalski** [theia-ide/theia-rust-extension#11]
Hi!

I tried building myself a theia-full docker image, added rls and I don't know what else I need to do to make it run. Is the extension operational?

**Comment by ricochet1k** [comment]
I have no idea, but I'm also trying to get this working. I know you are also going to need the `rust-analysis` and `rust-src` components, as well as `racer` if you want code completion. See also #12 that I just created, you probably have to manually specify a target for now.

**Comment by marcdumais-work** [comment]
Hi @njskalski ,

The `@theia/rust` extension that's published on NPM is a bit old, and most probably needs updating, following [breaking changes](https://github.com/theia-ide/theia/blob/master/CHANGELOG.md) in the Theia main repo, in the last few months. 

So an update is needed here first and the result published on NPM, before it can be successfully used in a recent version of the `theia-full` image. 

I tried building this extension as it currently is, and I can confirm it's not building ATM:

```
src/node/rust-contribution.ts(29,15): error TS2416: Property 'onDidFailSpawnProcess' in type 'RustContribution' is not assignable to the same property in base type 'BaseLanguageServerContribution'.
  Type '(error: Error) => void' is not assignable to type '(error: ProcessErrorEvent) => void'.
    Types of parameters 'error' and 'error' are incompatible.
      Type 'ProcessErrorEvent' is missing the following properties from type 'Error': name, message
src/node/rust-contribution.ts(30,37): error TS2345: Argument of type 'Error' is not assignable to parameter of type 'ProcessErrorEvent'.
  Property 'code' is missing in type 'Error' but required in type 'ProcessErrorEvent'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/opt/ericsson-dev/theia-rust-extension/node_modules/lerna/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 2,
  killed: false,
  stdout:
   'yarn run v1.15.2\n$ yarn run clean && yarn run build\n$ rimraf lib\n$ tsc\nsrc/node/rust-contribution.ts(29,15): error TS2416: Property \'onDidFailSpawnProcess\' in type \'RustContribution\' is not assignable to the same property in base type \'BaseLanguageServerContribution\'.\n  Type \'(error: Error) => void\' is not assignable to type \'(error: ProcessErrorEvent) => void\'.\n    Types of parameters \'error\' and \'error\' are incompatible.\n      Type \'ProcessErrorEvent\' is missing the following properties from type \'Error\': name, message\nsrc/node/rust-contribution.ts(30,37): error TS2345: Argument of type \'Error\' is not assignable to parameter of type \'ProcessErrorEvent\'.\n  Property \'code\' is missing in type \'Error\' but required in type \'ProcessErrorEvent\'.\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr:
   'error Command failed with exit code 2.\nerror Command failed with exit code 2.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run prepare',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.
```

**Comment by akosyakov** [comment]
It's because of https://github.com/theia-ide/theia/issues/4930 who broke should fix it to learn to care, i don't want to review each PR for compatibility myself

**Comment by marcdumais-work** [comment]
@njskalski FYI the `next` version of Theia now has a fix to bring back the compatibility that was accidentally broken in February, causing this issue here. If your application uses `latest`, it will work again after next week's 0.6.0 Theia release, planned for April 25th.

cc: @ricochet1k
